### ISSUE TITLE
Downloading the meta of a dispatched boefje task results in a type error: Object of type Task is not JSON serialisable

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#1588] opened 2023-08-09 13:46 UTC
When a boefje task is running we provide the option to download its meta before it's completed. This currently doesn't work and results in an error:

![Image](https://github.com/minvws/nl-kat-coordination/assets/16188579/bf32f572-164d-4707-8876-3dd2638ea3dc)

**Comment by praseodym** [comment] 2023-08-09 13:49
Duplicate of #1523

**Closed by praseodym** 2023-08-09 13:49 UTC
Labels: bug
