### ISSUE TITLE
TypeError on submit of Question ooi

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3668] opened 2024-10-10 13:33 UTC
**Describe the bug**
When submitting a Question ooi a Type error is thrown

**To Reproduce**

1. Go to Objects
2. Click on the csp question ooi.
3. Submit without changing data.

**Expected behavior**
Question oois can be submitted.

**Screenshots**
![image](https://github.com/user-attachments/assets/ca2385b4-6a12-45a5-8502-a08bef707274)

**OpenKAT version**
main

**Comment by Donnype** [comment] 2024-10-10 14:12
Duplicate of https://github.com/minvws/nl-kat-coordination/issues/3628

**Closed by Donnype** 2024-10-10 14:12 UTC
Labels: bug, regression
