### ISSUE TITLE
Show run time of plugin

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1578] opened 2023-08-08 12:22 UTC
**Is your feature request related to a problem? Please describe.**
Currently it is not clear from the interface how long a plugin (boefje, normalizer, bit) took to complete its tasks.

**Describe the solution you'd like**
- [ ] Showing the time each plugin took for each task in the interface
- [ ] Being able to filter on this value (e.g. show me all boefjes that took more than 1 hour to finish over the last 10 days)

**Comment by underdarknl** [comment] 2023-08-09 15:14
duplicate of https://github.com/minvws/nl-kat-coordination/issues/1161

**Closed by underdarknl** 2023-08-09 15:14 UTC
