### ISSUE TITLE
LaTeX exitcode 1

### ISSUE THREAD

**Issue by OnuxNemori** [minvws/nl-kat-coordination#195] opened 2022-10-04 11:55 UTC
_Please add one or more of the following labels to your issue:_
`backend`

**Describe the bug**
Keiko crashes when generating PDF.
Cause: PDFLatex exits with exitcode 1. Therefor it isn't returned by the application. 

**To Reproduce**
- default steps

**Expected behavior**
Should work

**Screenshots**
-

**Desktop
 - OS: Windows
 - Docker, WSL2.0

**Additional context**
```
[2022-10-04 11:41:41 +0000] [1] [INFO] [logging] [keiko.logging] Logging configuration loaded. [log_cfg=logging.json]
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
[2022-10-04 11:41:41 +0000] [1] [INFO] [templates] [keiko.templates] Loading samples in folder: /app/keiko/templates
[2022-10-04 11:41:41 +0000] [1] [INFO] [server] [uvicorn.error] Started server process [1]
[2022-10-04 11:41:41 +0000] [1] [INFO] [on] [uvicorn.error] Waiting for application startup.
[2022-10-04 11:41:41 +0000] [1] [INFO] [on] [uvicorn.error] Application startup complete.
[2022-10-04 11:41:41 +0000] [1] [INFO] [server] [uvicorn.error] Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     172.18.0.15:48646 - "POST /reports HTTP/1.1" 200 OK
INFO:     172.18.0.15:48646 - "GET /645dd596.keiko.pdf HTTP/1.1" 404 Not Found
[2022-10-04 11:41:44 +0000] [1] [INFO] [keiko] [keiko.keiko] Data shape validation successful. [report_id=645dd596] [template=bevindingenrapport]
[2022-10-04 11:41:44 +0000] [1] [INFO] [keiko] [keiko.keiko] Glossary loaded. [report_id=645dd596] [glossary=dutch.hiero.csv]
[2022-10-04 11:41:44 +0000] [1] [INFO] [keiko] [keiko.keiko] Template rendered. [report_id=645dd596] [template=bevindingenrapport]
[2022-10-04 11:41:44 +0000] [1] [INFO] [keiko] [keiko.keiko] Temporary folder created. [report_id=645dd596] [template=bevindingenrapport] [tmp_dirname=/tmp/tmp1kghbf99]
[2022-10-04 11:41:44 +0000] [1] [INFO] [keiko] [keiko.keiko] Assets copied. [report_id=645dd596] [template=bevindingenrapport]
INFO:     172.18.0.15:48646 - "GET /645dd596.keiko.pdf HTTP/1.1" 404 Not Found
INFO:     172.18.0.15:48646 - "GET /645dd596.keiko.pdf HTTP/1.1" 404 Not Found
[2022-10-04 11:41:46 +0000] [1] [INFO] [keiko] [keiko.keiko] pdflatex run. [report_id=645dd596] [template=bevindingenrapport] [command=pdflatex -synctex=1 -interaction=nonstopmode 645dd596.keiko.tex]
[2022-10-04 11:41:46 +0000] [1] [DEBUG] [keiko] [keiko.keiko] 1
[2022-10-04 11:41:46 +0000] [1] [DEBUG] [keiko] [keiko.keiko] This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./645dd596.keiko.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-01-09> xparse <2020-03-03>
(/usr/share/texlive/texmf-dist/tex/latex/base/report.cls
Document Class: report 2020/04/10 v1.4m Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size11.clo))
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.sty
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.def
(/usr/share/texlive/texmf-dist/tex/generic/babel/txtbabel.def))
(/usr/share/texlive/texmf-dist/tex/generic/babel-dutch/dutch.ldf))
(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)
(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty
(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)))
(/usr/share/texlive/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/share/texlive/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)
(/usr/share/texlive/texmf-dist/tex/generic/iftex/iftex.sty)
(/usr/share/texlive/texmf-dist/tex/generic/pdftexcmds/pdftexcmds.sty
(/usr/share/texlive/texmf-dist/tex/generic/infwarerr/infwarerr.sty))
(/usr/share/texlive/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty)
(/usr/share/texlive/texmf-dist/tex/generic/kvdefinekeys/kvdefinekeys.sty)
(/usr/share/texlive/texmf-dist/tex/generic/pdfescape/pdfescape.sty)
(/usr/share/texlive/texmf-dist/tex/latex/hycolor/hycolor.sty)
(/usr/share/texlive/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty)
(/usr/share/texlive/texmf-dist/tex/latex/auxhook/auxhook.sty)
(/usr/share/texlive/texmf-dist/tex/latex/kvoptions/kvoptions.sty)
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/share/texlive/texmf-dist/tex/generic/intcalc/intcalc.sty)
(/usr/share/texlive/texmf-dist/tex/generic/etexcmds/etexcmds.sty)
(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty)
(/usr/share/texlive/texmf-dist/tex/generic/bitset/bitset.sty
(/usr/share/texlive/texmf-dist/tex/generic/bigintcalc/bigintcalc.sty))
(/usr/share/texlive/texmf-dist/tex/latex/base/atbegshi-ltx.sty))
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/share/texlive/texmf-dist/tex/latex/base/atveryend-ltx.sty)
(/usr/share/texlive/texmf-dist/tex/latex/rerunfilecheck/rerunfilecheck.sty
(/usr/share/texlive/texmf-dist/tex/generic/uniquecounter/uniquecounter.sty)))
(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty)
(/usr/share/texlive/texmf-dist/tex/latex/lastpage/lastpage.sty)
(/usr/share/texlive/texmf-dist/tex/latex/ragged2e/ragged2e.sty
(/usr/share/texlive/texmf-dist/tex/latex/everysel/everysel.sty
(/usr/share/texlive/texmf-dist/tex/latex/everysel/everysel-2011-10-28.sty)))
(/usr/share/texlive/texmf-dist/tex/latex/titlepic/titlepic.sty)
(/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg))
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
No file 645dd596.keiko.aux.
(/usr/share/texlive/texmf-dist/tex/latex/caption/ltcaption.sty)
(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/share/texlive/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/share/texlive/texmf-dist/tex/latex/refcount/refcount.sty)
(/usr/share/texlive/texmf-dist/tex/generic/gettitlestring/gettitlestring.sty))
ABD: EverySelectfont initializing macros [1{/var/lib/texmf/fonts/map/pdftex/upd
map/pdftex.map} <./keiko.png>]
Hoofdstuk 1.

Package fancyhdr Warning: \headheight is too small (12.0pt): 
(fancyhdr)                Make it at least 21.04506pt, for example:
(fancyhdr)                \setlength{\headheight}{21.04506pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:

(fancyhdr)                \addtolength{\topmargin}{-9.04506pt}.


LaTeX Warning: Reference `LastPage' on page 1 undefined on input line 104.


Package fancyhdr Warning: \footskip is too small (30.0pt): 
(fancyhdr)                Make it at least 38.03705pt, for example:
(fancyhdr)                \setlength{\footskip}{38.03705pt}.

pdfTeX warning (ext4): destination with the same identifier (name{page.1}) has 
been already used, duplicate ignored
<to be read again> 
                   \relax 
l.104 \tableofcontents
                       [1]

Package fancyhdr Warning: \headheight is too small (12.0pt): 
(fancyhdr)                Make it at least 21.04506pt, for example:
(fancyhdr)                \setlength{\headheight}{21.04506pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:

(fancyhdr)                \addtolength{\topmargin}{-9.04506pt}.


LaTeX Warning: Reference `LastPage' on page 2 undefined on input line 106.


Package fancyhdr Warning: \footskip is too small (30.0pt): 
(fancyhdr)                Make it at least 38.03705pt, for example:
(fancyhdr)                \setlength{\footskip}{38.03705pt}.

[2]
Hoofdstuk 2.

Package fancyhdr Warning: \headheight is too small (12.0pt): 
(fancyhdr)                Make it at least 21.04506pt, for example:
(fancyhdr)                \setlength{\headheight}{21.04506pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:

(fancyhdr)                \addtolength{\topmargin}{-9.04506pt}.


LaTeX Warning: Reference `LastPage' on page 3 undefined on input line 157.


Package fancyhdr Warning: \footskip is too small (30.0pt): 
(fancyhdr)                Make it at least 38.03705pt, for example:
(fancyhdr)                \setlength{\footskip}{38.03705pt}.

[3]
Hoofdstuk 3.

Underfull \hbox (badness 3612) in paragraph at lines 166--167
[]|\OT1/cmr/m/n/10.95 This web-site does not com-ply to the in-ter-net.nl

Overfull \hbox (24.0pt too wide) in alignment at lines 161--173
 [] [] 

Overfull \hbox (24.0pt too wide) in alignment at lines 189--201
 [] [] 

Package fancyhdr Warning: \headheight is too small (12.0pt): 
(fancyhdr)                Make it at least 21.04506pt, for example:
(fancyhdr)                \setlength{\headheight}{21.04506pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:

(fancyhdr)                \addtolength{\topmargin}{-9.04506pt}.


LaTeX Warning: Reference `LastPage' on page 4 undefined on input line 201.


Package fancyhdr Warning: \footskip is too small (30.0pt): 
(fancyhdr)                Make it at least 38.03705pt, for example:
(fancyhdr)                \setlength{\footskip}{38.03705pt}.

[4]
Overfull \hbox (24.0pt too wide) in alignment at lines 215--229
 [] [] 

Package fancyhdr Warning: \headheight is too small (12.0pt): 
(fancyhdr)                Make it at least 13.59999pt, for example:
(fancyhdr)                \setlength{\headheight}{13.59999pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:

(fancyhdr)                \addtolength{\topmargin}{-1.59999pt}.

[5]
Overfull \hbox (24.0pt too wide) in alignment at lines 249--263
 [] [] 
! Missing $ inserted.
<inserted text> 
                $
l.293 Aanbeveling & Implement TLS_
                                     FALLBACK_SCSV. \\
! Missing $ inserted.
<inserted text> 
                $
l.294 
        

Overfull \hbox (24.0pt too wide) in alignment at lines 283--297
 [] [] 

Package fancyhdr Warning: \headheight is too small (12.0pt): 
(fancyhdr)                Make it at least 13.59999pt, for example:
(fancyhdr)                \setlength{\headheight}{13.59999pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:

(fancyhdr)                \addtolength{\topmargin}{-1.59999pt}.

[6]

Package fancyhdr Warning: \headheight is too small (12.0pt): 
(fancyhdr)                Make it at least 13.59999pt, for example:
(fancyhdr)                \setlength{\headheight}{13.59999pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:

(fancyhdr)                \addtolength{\topmargin}{-1.59999pt}.

[7]
Hoofdstuk 4.

Overfull \hbox (24.0pt too wide) in alignment at lines 318--319
 [] [] 

Overfull \hbox (64.54729pt too wide) in paragraph at lines 321--321
[]|\OT1/cmr/m/n/10.95 hrefhttps://www.first.org/cvss/.| 

Overfull \hbox (10.70972pt too wide) in paragraph at lines 326--326
[]|\OT1/cmr/m/n/10.95 Informatiebeveiliging| 

Overfull \hbox (24.0pt too wide) in alignment at lines 319--335
 [] [] 

Package fancyhdr Warning: \headheight is too small (12.0pt): 
(fancyhdr)                Make it at least 21.04506pt, for example:
(fancyhdr)                \setlength{\headheight}{21.04506pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:

(fancyhdr)                \addtolength{\topmargin}{-9.04506pt}.


LaTeX Warning: Reference `LastPage' on page 8 undefined on input line 335.


Package fancyhdr Warning: \footskip is too small (30.0pt): 
(fancyhdr)                Make it at least 38.03705pt, for example:
(fancyhdr)                \setlength{\footskip}{38.03705pt}.

[8]

Package lastpage Warning: Rerun to get the references right on input line 337.


AED: lastpage setting LastPage

Package fancyhdr Warning: \headheight is too small (12.0pt): 
(fancyhdr)                Make it at least 13.59999pt, for example:
(fancyhdr)                \setlength{\headheight}{13.59999pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:

(fancyhdr)                \addtolength{\topmargin}{-1.59999pt}.

[9] (./645dd596.keiko.aux)

LaTeX Warning: There were undefined references.


LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.


Package rerunfilecheck Warning: File `645dd596.keiko.out' has changed.
(rerunfilecheck)                Rerun to get outlines right
(rerunfilecheck)                or use package `bookmark'.

 )
(see the transcript file for additional information) </home/keiko/.texlive2020/
texmf-var/fonts/pk/ljfour/jknappen/ec/tcrm1095.600pk></usr/share/texlive/texmf-
dist/fonts/type1/public/amsfonts/cm/cmbx10.pfb></usr/share/texlive/texmf-dist/f
onts/type1/public/amsfonts/cm/cmbx12.pfb></usr/share/texlive/texmf-dist/fonts/t
ype1/public/amsfonts/cm/cmmi10.pfb></usr/share/texlive/texmf-dist/fonts/type1/p
ublic/amsfonts/cm/cmmi8.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/a
msfonts/cm/cmr10.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts
/cm/cmr12.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmr
17.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmsl10.pfb
>
Output written on 645dd596.keiko.pdf (10 pages, 355474 bytes).
SyncTeX written on 645dd596.keiko.synctex.gz.
Transcript written on 645dd596.keiko.log.

[2022-10-04 11:41:46 +0000] [1] [DEBUG] [keiko] [keiko.keiko] 
kpathsea: Running mktexpk --mfmode / --bdpi 600 --mag 1+0/600 --dpi 600 tcrm1095
mktexpk: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1+0/600; nonstopmode; input tcrm1095
This is METAFONT, Version 2.7182818 (TeX Live 2020/Debian) (preloaded base=mf)

(/usr/share/texlive/texmf-dist/fonts/source/jknappen/ec/tcrm1095.mf
(/usr/share/texlive/texmf-dist/fonts/source/jknappen/ec/exbase.mf)
(/usr/share/texlive/texmf-dist/fonts/source/jknappen/ec/tcrm.mf
(/usr/share/texlive/texmf-dist/fonts/source/jknappen/ec/txsymb.mf
 Ok (/usr/share/texlive/texmf-dist/fonts/source/jknappen/ec/exaccess.mf
 Ok) (/usr/share/texlive/texmf-dist/fonts/source/jknappen/ec/txpseudo.mf
 Ok) (/usr/share/texlive/texmf-dist/fonts/source/jknappen/ec/txaccent.mf
 Ok [0] [1] [2] [3] [4] [5] [6] [7] [8] [9] [10] [11] [12] [27] [29])
(/usr/share/texlive/texmf-dist/fonts/source/jknappen/ec/txgen.mf
 Ok [100] [109] [98] [99] [108])
(/usr/share/texlive/texmf-dist/fonts/source/jknappen/ec/txsymbol.mf
 Ok [13] [18] [21] [22] [23] [24] [25] [26] [28] [31] [32] [36] [39] [44]
[45] [46] [42] [47] [60] [61] [62] [77] [79] [87] [110] [91] [93] [94] [95]
[96] [126] [127] [128] [129] [130] [131] [132] [133] [134] [135] [136] [137]
[138] [139] [140] [141] [142] [143] [144] [145] [146] [147] [148] [149]
[150] [151] [152] [153] [154] [155] [156] [157] [158] [159] [160] [161]
[162] [163] [164] [165] [166] [167] [168] [169] [171] [172] [173] [174]
[175] [177] [176] [180] [181] [182] [183] [184] [187] [191] [214] [246])
(/usr/share/texlive/texmf-dist/fonts/source/jknappen/ec/txromod.mf
 Ok [48] [49] [50] [51] [52] [53] [54] [55] [56] [57])
(/usr/share/texlive/texmf-dist/fonts/source/jknappen/ec/txrsuper.mf
 Ok [185] [178] [179] [170] [186])
(/usr/share/texlive/texmf-dist/fonts/source/jknappen/ec/txrfract.mf
 Ok [188] [189] [190]) ) ) )
(some charht values had to be adjusted by as much as 0.06952pt)
Font metrics written on tcrm1095.tfm.
Output written on tcrm1095.600gf (128 characters, 25592 bytes).
Transcript written on tcrm1095.log.
mktexpk: /home/keiko/.texlive2020/texmf-var/fonts/pk/ljfour/jknappen/ec/tcrm1095.600pk: successfully generated.

INFO:     172.18.0.15:48646 - "GET /645dd596.keiko.pdf HTTP/1.1" 404 Not Found
[2022-10-04 11:41:48 +0000] [1] [INFO] [keiko] [keiko.keiko] pdflatex run. [report_id=645dd596] [template=bevindingenrapport] [command=pdflatex -synctex=1 -interaction=nonstopmode 645dd596.keiko.tex]
[2022-10-04 11:41:48 +0000] [1] [DEBUG] [keiko] [keiko.keiko] 1
[2022-10-04 11:41:48 +0000] [1] [DEBUG] [keiko] [keiko.keiko] This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./645dd596.keiko.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-01-09> xparse <2020-03-03>
(/usr/share/texlive/texmf-dist/tex/latex/base/report.cls
Document Class: report 2020/04/10 v1.4m Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size11.clo))
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.sty
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.def
(/usr/share/texlive/texmf-dist/tex/generic/babel/txtbabel.def))
(/usr/share/texlive/texmf-dist/tex/generic/babel-dutch/dutch.ldf))
(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)
(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty
(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)))
(/usr/share/texlive/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/share/texlive/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)
(/usr/share/texlive/texmf-dist/tex/generic/iftex/iftex.sty)
(/usr/share/texlive/texmf-dist/tex/generic/pdftexcmds/pdftexcmds.sty
(/usr/share/texlive/texmf-dist/tex/generic/infwarerr/infwarerr.sty))
(/usr/share/texlive/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty)
(/usr/share/texlive/texmf-dist/tex/generic/kvdefinekeys/kvdefinekeys.sty)
(/usr/share/texlive/texmf-dist/tex/generic/pdfescape/pdfescape.sty)
(/usr/share/texlive/texmf-dist/tex/latex/hycolor/hycolor.sty)
(/usr/share/texlive/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty)
(/usr/share/texlive/texmf-dist/tex/latex/auxhook/auxhook.sty)
(/usr/share/texlive/texmf-dist/tex/latex/kvoptions/kvoptions.sty)
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/share/texlive/texmf-dist/tex/generic/intcalc/intcalc.sty)
(/usr/share/texlive/texmf-dist/tex/generic/etexcmds/etexcmds.sty)
(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty)
(/usr/share/texlive/texmf-dist/tex/generic/bitset/bitset.sty
(/usr/share/texlive/texmf-dist/tex/generic/bigintcalc/bigintcalc.sty))
(/usr/share/texlive/texmf-dist/tex/latex/base/atbegshi-ltx.sty))
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/share/texlive/texmf-dist/tex/latex/base/atveryend-ltx.sty)
(/usr/share/texlive/texmf-dist/tex/latex/rerunfilecheck/rerunfilecheck.sty
(/usr/share/texlive/texmf-dist/tex/generic/uniquecounter/uniquecounter.sty)))
(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty)
(/usr/share/texlive/texmf-dist/tex/latex/lastpage/lastpage.sty)
(/usr/share/texlive/texmf-dist/tex/latex/ragged2e/ragged2e.sty
(/usr/share/texlive/texmf-dist/tex/latex/everysel/everysel.sty
(/usr/share/texlive/texmf-dist/tex/latex/everysel/everysel-2011-10-28.sty)))
(/usr/share/texlive/texmf-dist/tex/latex/titlepic/titlepic.sty)
(/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg))
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
(./645dd596.keiko.aux)
(/usr/share/texlive/texmf-dist/tex/latex/caption/ltcaption.sty)
(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/share/texlive/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/share/texlive/texmf-dist/tex/latex/refcount/refcount.sty)
(/usr/share/texlive/texmf-dist/tex/generic/gettitlestring/gettitlestring.sty))
(./645dd596.keiko.out) (./645dd596.keiko.out)
ABD: EverySelectfont initializing macros [1{/var/lib/texmf/fonts/map/pdftex/upd
map/pdftex.map} <./keiko.png>]
Hoofdstuk 1.

Package fancyhdr Warning: \headheight is too small (12.0pt): 
(fancyhdr)                Make it at least 21.04506pt, for example:
(fancyhdr)                \setlength{\headheight}{21.04506pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:

(fancyhdr)                \addtolength{\topmargin}{-9.04506pt}.


Package fancyhdr Warning: \footskip is too small (30.0pt): 
(fancyhdr)                Make it at least 38.03705pt, for example:
(fancyhdr)                \setlength{\footskip}{38.03705pt}.

pdfTeX warning (ext4): destination with the same identifier (name{page.1}) has 
been already used, duplicate ignored
<to be read again> 
                   \relax 
l.104 \tableofcontents
                       [1] (./645dd596.keiko.toc)

Package fancyhdr Warning: \headheight is too small (12.0pt): 
(fancyhdr)                Make it at least 21.04506pt, for example:
(fancyhdr)                \setlength{\headheight}{21.04506pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:

(fancyhdr)                \addtolength{\topmargin}{-9.04506pt}.


Package fancyhdr Warning: \footskip is too small (30.0pt): 
(fancyhdr)                Make it at least 38.03705pt, for example:
(fancyhdr)                \setlength{\footskip}{38.03705pt}.

[2]
Hoofdstuk 2.

Package fancyhdr Warning: \headheight is too small (12.0pt): 
(fancyhdr)                Make it at least 21.04506pt, for example:
(fancyhdr)                \setlength{\headheight}{21.04506pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:

(fancyhdr)                \addtolength{\topmargin}{-9.04506pt}.


Package fancyhdr Warning: \footskip is too small (30.0pt): 
(fancyhdr)                Make it at least 38.03705pt, for example:
(fancyhdr)                \setlength{\footskip}{38.03705pt}.

[3]
Hoofdstuk 3.

Underfull \hbox (badness 3612) in paragraph at lines 166--167
[]|\OT1/cmr/m/n/10.95 This web-site does not com-ply to the in-ter-net.nl

Overfull \hbox (24.0pt too wide) in alignment at lines 161--173
 [] [] 

Overfull \hbox (24.0pt too wide) in alignment at lines 189--201
 [] [] 

Package fancyhdr Warning: \headheight is too small (12.0pt): 
(fancyhdr)                Make it at least 21.04506pt, for example:
(fancyhdr)                \setlength{\headheight}{21.04506pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:

(fancyhdr)                \addtolength{\topmargin}{-9.04506pt}.


Package fancyhdr Warning: \footskip is too small (30.0pt): 
(fancyhdr)                Make it at least 38.03705pt, for example:
(fancyhdr)                \setlength{\footskip}{38.03705pt}.

[4]
Overfull \hbox (24.0pt too wide) in alignment at lines 215--229
 [] [] 

Package fancyhdr Warning: \headheight is too small (12.0pt): 
(fancyhdr)                Make it at least 13.59999pt, for example:
(fancyhdr)                \setlength{\headheight}{13.59999pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:

(fancyhdr)                \addtolength{\topmargin}{-1.59999pt}.

[5]
Overfull \hbox (24.0pt too wide) in alignment at lines 249--263
 [] [] 
! Missing $ inserted.
<inserted text> 
                $
l.293 Aanbeveling & Implement TLS_
                                     FALLBACK_SCSV. \\
! Missing $ inserted.
<inserted text> 
                $
l.294 
        

Overfull \hbox (24.0pt too wide) in alignment at lines 283--297
 [] [] 

Package fancyhdr Warning: \headheight is too small (12.0pt): 
(fancyhdr)                Make it at least 13.59999pt, for example:
(fancyhdr)                \setlength{\headheight}{13.59999pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:

(fancyhdr)                \addtolength{\topmargin}{-1.59999pt}.

[6]

Package fancyhdr Warning: \headheight is too small (12.0pt): 
(fancyhdr)                Make it at least 13.59999pt, for example:
(fancyhdr)                \setlength{\headheight}{13.59999pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:

(fancyhdr)                \addtolength{\topmargin}{-1.59999pt}.

[7]
Hoofdstuk 4.

Overfull \hbox (24.0pt too wide) in alignment at lines 318--319
 [] [] 

Overfull \hbox (64.54729pt too wide) in paragraph at lines 321--321
[]|\OT1/cmr/m/n/10.95 hrefhttps://www.first.org/cvss/.| 

Overfull \hbox (10.70972pt too wide) in paragraph at lines 326--326
[]|\OT1/cmr/m/n/10.95 Informatiebeveiliging| 

Overfull \hbox (24.0pt too wide) in alignment at lines 319--335
 [] [] 

Package fancyhdr Warning: \headheight is too small (12.0pt): 
(fancyhdr)                Make it at least 21.04506pt, for example:
(fancyhdr)                \setlength{\headheight}{21.04506pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:

(fancyhdr)                \addtolength{\topmargin}{-9.04506pt}.


Package fancyhdr Warning: \footskip is too small (30.0pt): 
(fancyhdr)                Make it at least 38.03705pt, for example:
(fancyhdr)                \setlength{\footskip}{38.03705pt}.

[8] 
AED: lastpage setting LastPage

Package fancyhdr Warning: \headheight is too small (12.0pt): 
(fancyhdr)                Make it at least 13.59999pt, for example:
(fancyhdr)                \setlength{\headheight}{13.59999pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:

(fancyhdr)                \addtolength{\topmargin}{-1.59999pt}.

[9] (./645dd596.keiko.aux) )
(see the transcript file for additional information) </home/keiko/.texlive2020/
texmf-var/fonts/pk/ljfour/jknappen/ec/tcrm1095.600pk></usr/share/texlive/texmf-
dist/fonts/type1/public/amsfonts/cm/cmbx10.pfb></usr/share/texlive/texmf-dist/f
onts/type1/public/amsfonts/cm/cmbx12.pfb></usr/share/texlive/texmf-dist/fonts/t
ype1/public/amsfonts/cm/cmmi10.pfb></usr/share/texlive/texmf-dist/fonts/type1/p
ublic/amsfonts/cm/cmmi8.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/a
msfonts/cm/cmr10.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts
/cm/cmr12.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmr
17.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmsl10.pfb
>
Output written on 645dd596.keiko.pdf (10 pages, 359160 bytes).
SyncTeX written on 645dd596.keiko.synctex.gz.
Transcript written on 645dd596.keiko.log.

[2022-10-04 11:41:48 +0000] [1] [DEBUG] [keiko] [keiko.keiko] 
[2022-10-04 11:41:48 +0000] [1] [INFO] [keiko] [keiko.keiko] Report copied to reports folder. [report_id=645dd596] [template=bevindingenrapport] [output_file=reports/645dd596.keiko.pdf]
INFO:     172.18.0.15:48646 - "GET /645dd596.keiko.pdf HTTP/1.1" 200 OK

```

**Comment by underdarknl** [comment] 2023-04-25 09:42
Are we still seeing this behavior?

**Comment by praseodym** [comment] 2023-05-01 08:47
This is most likely a duplicate of #678. If this error keeps occurring on the newest version, please re-open this issue or create a new one.

**Closed** 2023-05-01 08:47 UTC
Labels: keiko
