### ISSUE TITLE
Origin of OOI

### ISSUE THREAD

**Issue by noamblitz** [minvws/nl-kat-coordination#596] opened 2023-03-28 15:07 UTC
At present, there are OOIs that are present in KAT, but their origins are unclear. These OOIs can be associated with hostnames that have corresponding DNS records from different levels of nameservers. It would be useful to have a feature that can determine the shortest path of inheritance/observation to an OOI with a specified scan level. This feature can be implemented as a manual query and need not be displayed on every detail page.

**Comment by TwistMeister** [comment] 2023-04-03 11:25
Duplicate of https://github.com/minvws/nl-kat-coordination/issues/501

**Closed** 2023-04-03 11:25 UTC
Labels: frontend, rocky
