### ISSUE TITLE
Aggregate reports does not have sub reports 

### ISSUE THREAD

**Issue by Rieven** [minvws/nl-kat-coordination#3823] opened 2024-11-11 13:37 UTC
When creating an aggregate report it should:

- Save all sub reports from the list of report types 
- Attach the parent report id to the sub reports
- List sub reports for aggregate reports
- Naming for sub reports will be the same as concatenated report which is the {report_type} for {ooi}

**Comment by noamblitz** [comment] 2024-11-11 13:39
https://github.com/minvws/nl-kat-coordination/blob/bf3267af8aa78ae454ceb7d2e8534fcb583a0a80/rocky/reports/views/mixins.py#L242

Here

**Comment by underdarknl** [comment] 2024-11-14 20:23
> https://github.com/minvws/nl-kat-coordination/blob/bf3267af8aa78ae454ceb7d2e8534fcb583a0a80/rocky/reports/views/mixins.py#L242
> 
> Here the OOIs also have to be saved to Octopoes

ideally, a normlizer would pick up these report raw files, and create the ooi's.
Since that's async, and slow, we'd probably want to add them to Octopoes directly from rocky too, to avoid delays that bother the user (probably less relevant once the reports are not directly created in rocky anymore)

**Comment by underdarknl** [comment] 2024-11-14 20:24
Duplicate of #3805

**Closed by underdarknl** 2024-11-14 20:24 UTC
Labels: bug
