### ISSUE TITLE
Command `make docs` creates files that are not inside the .gitignore

### ISSUE THREAD

**Issue by Souf149** [minvws/nl-kat-coordination#3103] opened 2024-06-19 08:16 UTC
**Describe the bug**
When you run `make docs` with no local changes, after this command there will be 5 new files added which would be taken with you on the next commit. Is this intended behavior?

**To Reproduce**

1. Install a fresh copy of OpenKAT
2. Run `make docs` in the root folder
3. Run `git status` to see that you have untracked files

**Expected behavior**
When running `make` commands, generally no files should be changed that are being tracked by the version control.

**Screenshots**
`git status` after running `make docs`
![image](https://github.com/minvws/nl-kat-coordination/assets/34127049/95647f3e-b06e-4026-b910-452eff7e7af6)

**OpenKAT version**
1.51.1 (latest)

**Comment by ammar92** [comment] 2024-06-19 08:51
Duplicate of https://github.com/minvws/nl-kat-coordination/issues/3013?

**Closed** 2024-06-19 13:25 UTC
Labels: bug

**Comment by Souf149** [comment] 2024-06-19 13:41
My bad! I can not remember creating this
