### ISSUE TITLE
Remove `Job` model from Rocky?

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#453] opened 2023-03-07 15:40 UTC
This is legacy^2

**Comment by underdarknl** [comment] 2023-03-07 16:32
Wouldn't we want to introduce an object again which handles the data that a Job now has, but also implements methods to restart the job?
I'd say this is more useful than just a Dict, and is something that could be handed a Scheduler-client-instance to communicate trough. They could also be created by the Scheduler-client.

**Comment by Donnype** [comment] 2023-03-07 17:59
It's mostly the Job table in Rocky I'm referring to. This seems to have 0 uses in Rocky.

**Comment by ammar92** [comment] 2023-05-15 12:25
This is a duplicate of https://github.com/minvws/nl-kat-coordination/issues/352

**Closed** 2023-05-15 12:29 UTC
Labels: tech-debt, chore
