### ISSUE TITLE
Multi report gives RecursionError

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#3640] opened 2024-10-08 10:17 UTC
**Describe the bug**
When trying to create a Multi Report, a RecursionError is thrown.

**To Reproduce**

1. Go to 'Reports'
2. Click on 'Multi report'
3. See the error

**Expected behavior**
Should go to the multi report flow.

**Screenshots**
![Image](https://github.com/user-attachments/assets/40b1341a-2ee7-4d0a-b9d3-786dc4f34740)

**OpenKAT version**
main

**Comment by dekkers** [comment] 2024-10-11 11:06
https://sonarcloud.io/project/issues?fileUuids=AY_dVgiJGgO8mB8X8A1A&issueStatuses=OPEN%2CCONFIRMED&id=minvws_nl-kat-coordination&open=AZJXrRL4dScQYYDmeUzN

**Comment by dekkers** [comment] 2024-10-15 08:50
Closing, at this is a duplicate of #3623

**Closed by dekkers** 2024-10-15 08:50 UTC
Labels: bug, report
