### ISSUE TITLE
Boefje variant json schema contains lot of null values

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3569] opened 2024-09-23 10:39 UTC
**Describe the bug**
During the QA of #3557 it appeared that the API used by the boefje variants does something silly with/near the JSON schema. 

**To Reproduce**

1. Go to Nmap TCP boefje and create a variant.
2. Observe that the JSON schema contains a lot of 'null' values. 
3. Open the newly created boefje variant in the Katalogus.
4. Observe that the settings page 'exploded' with variables. 
5. Running the boefje variant results in an error. The output from raw is posted below. 

**Expected behavior**
The JSON schema for the nmap options should be displayed on the katalogus page. 

**Screenshots**
JSON schema when creating a new boefje variant:
![image](https://github.com/user-attachments/assets/3d4d7070-f3b3-4cf3-bb0b-f1ba8f546091)

Viewing this new boefje variant in the katalogus:
![image](https://github.com/user-attachments/assets/558f7abd-6c9a-4334-b6f4-0db349a8d529)

**OpenKAT version**
main

**Contents RAW file** 
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/oci_adapter.py", line 46, in <module>
    main()
  File "/app/oci_adapter.py", line 13, in main
    boefje_input = httpx.get(input_url).json()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 766, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by underdarknl** [comment] 2024-09-23 12:13
It looks like this is a regression due to @ammar92 's migration of some fieldnames / or should be fixed by the migration.
What you are seeing here is the Internal Pydantic Schema of the Boefje, not the boefjes JsonSchema as defined in our plugin itself.
I think we made an error in merging https://github.com/minvws/nl-kat-coordination/pull/3557

**Closed** 2024-09-24 08:14 UTC
Labels: bug, backend
